add auto make torrent;

diff --git a/config/func b/config/func
--- a/config/func
+++ b/config/func
@@ -341,6 +341,26 @@ mtorrent()
 	[ "${f_file}" = "${f_path}" ] || cd -
 }
 
+mktor()
+{
+	#temporary usage
+	local file="$1"
+	local msg="[Created by HPCENC](https://github.com/jiaolovekt/HPCENC)"
+	if [ -z "$CONFIGDIR" ] ; then
+		[ -d "${ENCROOT}/config" ] && CONFIGDIR="${ENCROOT}/config" #try
+	fi
+		
+	if ! [ -f "$CONFIGDIR/trackers.txt" ] ; then
+		logg "trackers.txt not found" err 
+		return 1
+	fi
+	if [ $(wc -l "$CONFIGDIR/trackers.txt" | cut -d ' ' -f 1) -gt 100 ] ; then
+		mtorrent "$file" "$CONFIGDIR/trackers.txt" "$msg"
+	else
+		logg "lines in trackers.txt lt 100" err
+	fi
+}
+
 update_trlist()
 {
 	# update trackers from https://github.com/ngosang/trackerslist
